### ISSUE TITLE
Add support to light theme

### ISSUE THREAD

**Issue by stra1g** [gabrielmaialva33/vs-owldarker-theme#1]
Your theme is perfect for night, but I code in morning so I would love to have the possibility to choose a light theme with this color schema! :)) <3

**Comment by gabrielmaialva33** [comment]
Hey there! 😄✨

Thank you so much for your kind words and brilliant suggestion! 💡

We are absolutely thrilled to hear that you are enjoying our theme during the night time. 🌙 We understand how important it is to have a theme that suits all times of the day, especially for those bright and productive mornings! ☀️

Your suggestion to introduce a light theme variant with the beloved color schema is a fabulous idea, and we're already buzzing with excitement to work on this! 🌈 We want to ensure that your coding experience is comfortable and enjoyable at all hours!

Please stay tuned for updates, and we hope to bring a splash of brightness to your morning coding sessions very soon! ☀️💻💖

Happy Coding,
The OwlDarker Team 😊✨

**Comment by stra1g** [comment]
some update?
